bash: ./quest3.py: Отказано в доступе
